################################################################################
#
# Build script for project
#
################################################################################

# Add source files here
EXECUTABLE	:= barnesHut
# Cuda source files (compiled with cudacc)
CUFILES		:= BurtscherGCG.2.2.cu
# C/C++ source files (compiled with gcc / c++)
CCFILES		:= 


# Additional libraries needed by the project
USECUBLAS       := 1

################################################################################
# Rules and targets

include ../../common/common.mk
