################################################################################
#
# Build script for project
#
################################################################################

# Add source files here
EXECUTABLE	:= dotProd
# Cuda source files (compiled with cudacc)
CUFILES		:= dotProd.cu
# C/C++ source files (compiled with gcc / c++)
CCFILES		:= 

# Additional libraries needed by the project
USECUBLAS       := 1

################################################################################
# Rules and targets

include ../../common/common.mk
